# Generated by Django 5.1 on 2025-10-28 18:22

import django.core.validators
import django.db.models.deletion
import entrance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "date_of_birth",
                    models.DateField(validators=[entrance.models.validate_age]),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("widowed", "Widowed"),
                            ("divorced", "Divorced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(default="Cameroonian", max_length=100),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("congregation_name", models.CharField(max_length=200)),
                ("years_in_congregation", models.IntegerField()),
                ("pastor_name", models.CharField(max_length=200)),
                ("pastor_phone", models.CharField(max_length=20)),
                ("pastor_email", models.EmailField(max_length=254)),
                ("chairperson_name", models.CharField(max_length=200)),
                ("chairperson_phone", models.CharField(max_length=20)),
                ("chairperson_email", models.EmailField(max_length=254)),
                ("last_school_attended", models.CharField(max_length=200)),
                ("graduation_year", models.IntegerField()),
                (
                    "birth_certificate",
                    models.FileField(
                        upload_to="applications/birth_certificates/",
                        validators=[
                            entrance.models.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                (
                    "transcripts",
                    models.FileField(
                        upload_to="applications/transcripts/",
                        validators=[
                            entrance.models.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                (
                    "gce_a_level",
                    models.FileField(
                        upload_to="applications/gce_a_level/",
                        validators=[
                            entrance.models.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                (
                    "gce_o_level",
                    models.FileField(
                        upload_to="applications/gce_o_level/",
                        validators=[
                            entrance.models.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                (
                    "passport_photo",
                    models.ImageField(
                        upload_to="applications/photos/",
                        validators=[
                            entrance.models.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        help_text="Maximum 2000 characters",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=200)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField()),
                ("exam_time", models.TimeField()),
                ("registration_deadline", models.DateField()),
                ("max_applicants", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exam Session",
                "verbose_name_plural": "Exam Sessions",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="ExamVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("capacity", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exam Venue",
                "verbose_name_plural": "Exam Venues",
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("acceptance", "Acceptance Email"),
                            ("rejection", "Rejection Email"),
                            ("confirmation", "Application Confirmation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_to", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("was_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="entrance.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="assigned_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="entrance.examsession",
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="entrance.examvenue",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="preferred_venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="entrance.examvenue",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "-created_at"], name="entrance_ap_status_ac1095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["email"], name="entrance_ap_email_210e54_idx"),
        ),
    ]
