# Generated by Django 5.1 on 2025-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gradescalerule',
            name='examination_min_gra_eab956_idx',
        ),
        migrations.RenameField(
            model_name='gradescalerule',
            old_name='max_grade',
            new_name='max_marks',
        ),
        migrations.RenameField(
            model_name='gradescalerule',
            old_name='min_grade',
            new_name='min_marks',
        ),
        migrations.AlterUniqueTogether(
            name='gradescalerule',
            unique_together={('min_marks', 'max_marks', 'grade_scale')},
        ),
        migrations.AddIndex(
            model_name='gradescalerule',
            index=models.Index(fields=['min_marks', 'max_marks', 'grade_scale'], name='examination_min_mar_838741_idx'),
        ),
    ]
